### ISSUE TITLE
Roadmap to v2

### ISSUE THREAD

**Issue by julien-c** [julien-c/Circular#51]
- [ ] Rewrite daemon (1 day)
- [ ] Switch hosting and document install to e.g. Digital Ocean (0.5 day)
- [ ] Rewrite API (1 day)
- [ ] Document API (0.5 day)
- [ ] Improve frontend (2 days)

**Comment by BenjaminHCCarr** [comment]
Any updates on roadmap?
